### ISSUE TITLE
Unable to Save Bandwidth Information on the General Output Module

### ISSUE THREAD

**Issue by sidneymurray** [lcnbeapp/beapp#24]
Hi! I am analyzing EEG data using BEAPP for my dissertation, but am new to it. I am having a repeated issue with the Output Module Settings panel, where every time I type in my bandwidth names and ranges (Delta 1-4; Theta 4-8; Alpha 8-13; Beta 13-30; Gamma 30-60; High Gamma 60-125), whether I click "Next" or "Save" I get the error sound and the window pane completely closes. So I never even get to see the PSD panel to enter my Hanning Window information. Can anyone help me?

**Comment by ybraverman** [comment]
Hi Sidney!

Thanks for reaching out, could you tell me when you downloaded beapp? We made an update on Nov 30th that should have fixed this issue, so I'd first recommend re-downloading and seeing if that fixes things. If you downloading after Nov 30th let us know and we can take another look!

**Comment by ybraverman** [comment]
Hi Sidney, 

Thanks for re-downloading! We have not had issues with finding the source data files - usually when this happens it's because the source directory is set incorrectly or inadvertently having beapp load the wrong file info table - see my other comment for some next steps to troubleshoot this, would be happy to connect over zoom if you're still having trouble from there!
